// Mục "Phạm vi Việt Nam: quy tắc liên kết chính" của trang PRO-SCORE1000™: quy tắc, cơ sở khoa học, hiệu chuẩn bằng ORCID, hội đồng mô phỏng và quyết định. Số liệu lấy từ public/data/abroad-decision.json (scripts/abroad-decision.mjs).
// Bản chữ tĩnh cho công cụ tìm kiếm nằm trong scripts/build-seo-pages.mjs (/pro-score/): sửa một nơi thì sửa cả hai.
import { useEffect, useState } from "react";
import type { Lang } from "./i18n";

type Run = { run: number; n: number; seed: number; fields: boolean; median: number; p25: number; p75: number };
type Field = { id: string; vi: string; experts: number; profiles: number; bayesEqualCost: number };
type Ver = { bootstrap: { resamples: number; labeled: number; bayesEqualCost: { lo95: number; hi95: number }; panelConsensus: { lo95: number; hi95: number } }; mixes: { label: string; median: number }[] };
type Factor = { threshold: number; profiles: number; expectedVn: number; tagged: number; atThreshold: { t: number; expectedWronglyExcluded: number; expectedWronglyAdmitted: number }; impliedCostRatio: { from: number; to: number } | null; runs: Run[]; stances: { id: string; vi: string; median: number }[]; calibration: { labeled: number; strata: { lo: number; hi: number; n: number; vnShare: number }[] }; hist: number[]; verification: Ver | null; fieldsRun: Field[] | null };
export type AbroadDecision = { rule: { years: number[]; window: number; recentMinWorks: number; minWorks: number; recentMinShare: number; maxVnShare: number }; factors: { recent: Factor; overall: Factor } };
const STANCE_EN: Record<string, string> = { inclusive: "Inclusive (avoid missing Vietnamese scientists abroad and multi-affiliated scientists)", balanced: "Balanced (both kinds of error weigh the same)", strict: "Strict (prefer a table of people whose primary affiliation is in Vietnam)" };
export const REFS: string[] = [
  "Bhattacharjee, Y. (2011). Saudi universities offer cash in exchange for academic prestige. Science, 334(6061), 1344–1345.",
  "Bornmann, L., & Bauer, J. (2015). Which of the world’s institutions employ the most highly cited researchers? An analysis of the data from highlycited.com. Journal of the Association for Information Science and Technology (arXiv:1407.2037).",
  "Clarivate (2023–2025). Highly Cited Researchers: methodology, FAQs and statement on researcher affiliations (clarivate.com/highly-cited-researchers).",
  "Dalkey, N., & Helmer, O. (1963). An experimental application of the Delphi method to the use of experts. Management Science, 9(3), 458–467.",
  "DeGroot, M. H. (1974). Reaching a consensus. Journal of the American Statistical Association, 69(345), 118–121.",
  "French, J. R. P. (1956). A formal theory of social power. Psychological Review, 63(3), 181–194.",
  "Hottenrott, H., & Lawson, C. (2017). A first look at multiple institutional affiliations: a study of authors in Germany, Japan and the UK. Scientometrics, 111(1), 285–295. doi:10.1007/s11192-017-2257-6",
  "Hottenrott, H., Rose, M. E., & Lawson, C. (2021). The rise of multiple institutional affiliations in academia. Journal of the Association for Information Science and Technology.",
  "Barlow, R. E., Bartholomew, D. J., Bremner, J. M., & Brunk, H. D. (1972). Statistical inference under order restrictions. Wiley (hồi quy đơn điệu / isotonic regression).",
];
function FactorBlock({ f, name, vi, num, rule, kind }: { f: Factor; name: string; vi: boolean; num: (n: number, d?: number) => string; rule: AbroadDecision["rule"]; kind: "recent" | "overall" }) {
  const hmax = Math.max(...f.hist), stanceName = (s: { id: string; vi: string }) => (vi ? s.vi : STANCE_EN[s.id]);
  return (
    <div>
      <h4>{name}</h4>
      <p>{vi ? `Hiệu chuẩn bằng ORCID (${num(f.calibration.labeled)} hồ sơ có nhãn): tỉ lệ hồ sơ hiện có nơi làm việc tại Việt Nam trên ORCID, theo từng mức ${kind === "recent" ? "tỉ lệ công bố gần đây có liên kết Việt Nam (năm thấp nhất)" : "tỉ lệ dài hạn có liên kết Việt Nam"}:` : `ORCID calibration (${num(f.calibration.labeled)} labelled profiles): share of profiles currently employed in Vietnam on ORCID, by level of ${kind === "recent" ? "recent publications with a Vietnam affiliation (weakest year)" : "long-run share with a Vietnam affiliation"}:`}</p>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Mức tỉ lệ" : "Share level"}</th><th>{vi ? "Số hồ sơ có nhãn" : "Labelled profiles"}</th><th>{vi ? "Hiện làm việc tại VN (ORCID)" : "Currently in Vietnam (ORCID)"}</th></tr></thead>
        <tbody>{f.calibration.strata.map((s) => <tr key={s.lo}><td>{s.lo}–{s.hi}%</td><td>{num(s.n)}</td><td>{num(s.vnShare)}%</td></tr>)}</tbody></table></div>
      <div className="abh" role="img" aria-label={vi ? "Phân bố số hồ sơ theo mức tỉ lệ" : "Profiles by share level"}>{f.hist.map((v, i) => <i key={i} title={`${i * 5}–${i * 5 + 5}%: ${num(v)}`} style={{ height: `${Math.max(2, Math.round((v / hmax) * 100))}%` }} className={i * 5 < f.threshold ? "lo" : undefined} />)}</div>
      <p className="meta">{vi ? `Trục ngang: 0% đến 100%, mỗi cột 5% (${num(f.profiles)} hồ sơ); cột đậm là vùng dưới ngưỡng ${f.threshold}%.` : `Horizontal axis: 0% to 100%, 5% per bar (${num(f.profiles)} profiles); darker bars lie below the ${f.threshold}% threshold.`}</p>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Lần mô phỏng" : "Run"}</th><th>{vi ? "Số chuyên gia" : "Experts"}</th><th>{vi ? "Hạt giống" : "Seed"}</th><th>{vi ? "Trung vị đồng thuận (%)" : "Consensus median (%)"}</th><th>{vi ? "Tứ phân vị (%)" : "Interquartile (%)"}</th></tr></thead>
        <tbody>{f.runs.map((r) => <tr key={r.run}><td>{vi ? `Lần ${r.run}${r.fields ? " (nhiều lĩnh vực)" : ""}` : `Run ${r.run}${r.fields ? " (multi-field)" : ""}`}</td><td>{num(r.n)}</td><td>{r.seed}</td><td>{num(r.median, 1)}</td><td>{num(r.p25, 1)} – {num(r.p75, 1)}</td></tr>)}</tbody></table></div>
      <p>{vi ? "Lần 1 theo ba lập trường:" : "Run 1 by stance:"} {f.stances.map((x) => `${stanceName(x)}: ${num(x.median, 1)}%`).join("; ")}.</p>
      {f.verification && <p>{vi ? `Kiểm định lại: bootstrap ${f.verification.bootstrap.resamples} lần trên mẫu ORCID (hiệu chuẩn lại mỗi lần) cho khoảng tin cậy 95% của ngưỡng tối ưu là ${f.verification.bootstrap.bayesEqualCost.lo95}–${f.verification.bootstrap.bayesEqualCost.hi95}% và của trung vị hội đồng là ${f.verification.bootstrap.panelConsensus.lo95}–${f.verification.bootstrap.panelConsensus.hi95}%; đổi cơ cấu lập trường cho kết quả từ ${Math.min(...f.verification.mixes.map((m) => m.median))}% (toàn bao trùm) đến ${Math.max(...f.verification.mixes.map((m) => m.median))}% (toàn chặt chẽ).` : `Re-check: ${f.verification.bootstrap.resamples} bootstrap resamples of the ORCID sample (recalibrated each time) give a 95% interval of ${f.verification.bootstrap.bayesEqualCost.lo95}–${f.verification.bootstrap.bayesEqualCost.hi95}% for the optimal threshold and ${f.verification.bootstrap.panelConsensus.lo95}–${f.verification.bootstrap.panelConsensus.hi95}% for the panel median; changing the stance mix gives from ${Math.min(...f.verification.mixes.map((m) => m.median))}% (all inclusive) to ${Math.max(...f.verification.mixes.map((m) => m.median))}% (all strict).`}</p>}
      {f.fieldsRun && <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Nhóm lĩnh vực (lần 3)" : "Field group (run 3)"}</th><th>{vi ? "Hồ sơ" : "Profiles"}</th><th>{vi ? "Chuyên gia" : "Experts"}</th><th>{vi ? "Ngưỡng tối ưu, hai sai sót nặng như nhau (%)" : "Optimal threshold, equal errors (%)"}</th></tr></thead>
        <tbody>{f.fieldsRun.map((x) => <tr key={x.id}><td>{x.vi}</td><td>{num(x.profiles)}</td><td>{x.experts}</td><td>{x.profiles < 200 ? (vi ? "chưa đủ dữ liệu để ước lượng" : "too little data to estimate") : num(x.bayesEqualCost)}</td></tr>)}</tbody></table></div>}
      <p><b>{vi ? `Quyết định của hội đồng: ${f.threshold}%.` : `Panel decision: ${f.threshold}%.`}</b> {vi ? `Bằng trung vị của ba trung vị đồng thuận, làm tròn đến số nguyên. Với ngưỡng này ${num(f.tagged)} trên ${num(f.profiles)} hồ sơ bị gắn nhãn; theo mô hình, kỳ vọng loại nhầm ${num(f.atThreshold.expectedWronglyExcluded)} hồ sơ làm việc tại Việt Nam và đưa nhầm ${num(f.atThreshold.expectedWronglyAdmitted)} hồ sơ không làm việc tại Việt Nam${f.impliedCostRatio ? `; tương ứng coi việc loại nhầm nặng gấp khoảng ${num(f.impliedCostRatio.from, 1)}–${num(f.impliedCostRatio.to, 1)} lần việc đưa nhầm` : ""}.` : `The median of the three consensus medians, rounded to an integer. At this threshold ${num(f.tagged)} of ${num(f.profiles)} profiles are tagged; by the model, about ${num(f.atThreshold.expectedWronglyExcluded)} profiles working in Vietnam are expected to be wrongly excluded and ${num(f.atThreshold.expectedWronglyAdmitted)} not working in Vietnam wrongly admitted${f.impliedCostRatio ? `; equivalent to treating wrongful exclusion as about ${num(f.impliedCostRatio.from, 1)}–${num(f.impliedCostRatio.to, 1)} times as serious as wrongful admission` : ""}.`}</p>
    </div>
  );
}
export function AbroadRule({ lang, num }: { lang: Lang; num: (n: number, d?: number) => string }) {
  const vi = lang === "vi";
  const [d, setD] = useState<AbroadDecision | null>(null);
  useEffect(() => { fetch("./data/abroad-decision.json").then((r) => r.json()).then(setD).catch(() => {}); }, []);
  if (!d) return null;
  const { rule } = d, r = d.factors.recent.threshold, t = d.factors.overall.threshold, yrs = rule.years.join(", ");
  return (
    <section className="psp-sec" id="pham-vi-viet-nam"><h2>{vi ? "Phạm vi Việt Nam: quy tắc “liên kết chính”" : "Vietnam scope: the “primary affiliation” rule"}</h2>
      <p>{vi ? "ProFind™ là bảng tra cứu và xếp hạng dành riêng cho nhà khoa học của các trường, viện Việt Nam. Để PRO-SCORE1000™ phản ánh đóng góp cho cộng đồng khoa học Việt Nam, một hồ sơ chỉ được xếp hạng khi liên kết chính của người đó ở Việt Nam." : "ProFind™ is a lookup and ranking table dedicated to scientists of Vietnamese universities and institutes. So that PRO-SCORE1000™ reflects contribution to the Vietnamese scientific community, a profile is ranked only when the person’s primary affiliation is in Vietnam."}</p>
      <aside className="psp-disc" role="note"><div>
        <b>{vi ? "Quy tắc" : "The rule"}</b>
        <p>{vi ? <><strong>1. Yếu tố gần đây (quan trọng nhất).</strong> Trong {rule.window} năm gần nhất ({yrs}), ở mỗi năm có công bố, tỉ lệ công trình mang liên kết cơ quan tại Việt Nam phải đạt tối thiểu <strong>{r}%</strong> (tính trên các công trình mà OpenAlex ghi cơ quan; cần ít nhất {rule.recentMinWorks} công trình trong cửa sổ này). Một năm mất liên kết Việt Nam thì không còn “liên tục”.</> : <><strong>1. Recent factor (most important).</strong> In each of the latest {rule.window} years ({yrs}) in which the profile published, the share of works carrying an affiliation in Vietnam must be at least <strong>{r}%</strong> (counted over works with an affiliation recorded in OpenAlex; at least {rule.recentMinWorks} such works in the window). A year without the Vietnam link breaks the “continuity”.</>}</p>
        <p>{vi ? <><strong>2. Yếu tố dài hạn</strong> (chỉ dùng khi chưa đủ công bố gần đây). Trên toàn bộ công trình có ghi cơ quan (tối thiểu {rule.minWorks} công trình), tỉ lệ có liên kết Việt Nam phải đạt tối thiểu <strong>{t}%</strong>.</> : <><strong>2. Long-run factor</strong> (used only when there are too few recent publications). Across all works with an affiliation recorded (at least {rule.minWorks}), the share with a Vietnam affiliation must be at least <strong>{t}%</strong>.</>}</p>
        <p>{vi ? "Hồ sơ không đạt được gắn nhãn “Liên kết chính ở nước ngoài” và không xếp hạng; hồ sơ vẫn hiển thị trên ProFind™. Hai ngưỡng do hội đồng chuyên gia mô phỏng quyết định (xem bên dưới), không phải do quản trị viên ấn định." : "A profile that fails is tagged “Primary affiliation abroad” and not ranked; it stays visible on ProFind™. Both thresholds are decided by the simulated expert panel (see below), not set by an administrator."}</p>
        <p>{vi ? "Không áp dụng cho: hồ sơ chưa đủ dữ liệu cơ quan; hồ sơ được quản trị viên xác nhận là ngoại lệ (danh sách công khai trong mã nguồn, tệp data/vn-confirmed.json). Chủ hồ sơ có thể gửi đính chính." : "Not applied to: profiles with too little affiliation data; profiles confirmed as exceptions by an administrator (public list in the source code, data/vn-confirmed.json). Profile owners may submit a correction."}</p>
        <p>{vi ? "Giới hạn này chỉ dành cho bảng Việt Nam. Nếu sau này ProFind™ mở rộng sang bảng phạm vi thế giới, bảng đó sẽ không có giới hạn này." : "This limit applies to the Vietnam table only. If ProFind™ later adds a worldwide table, that table will not have this limit."}</p>
      </div></aside>

      <h3>{vi ? "Cơ sở khoa học" : "Scientific basis"}</h3>
      <ul className="psp-ul">
        <li>{vi ? <><b>Liên kết chính được đọc từ công bố gần đây.</b> Clarivate (Highly Cited Researchers) định nghĩa liên kết chính là cơ quan nơi nhà nghiên cứu sinh sống, giữ vị trí chính và thực hiện phần lớn công việc, <i>thể hiện qua công bố gần đây</i>; liên kết danh dự hoặc nghiên cứu viên không được coi là liên kết chính nếu không chứng minh được làm việc thường trực (Clarivate, 2023–2025). Vì vậy yếu tố gần đây được đặt lên hàng đầu: người mới chuyển về Việt Nam vẫn được xếp hạng dù nhiều năm trước công bố ở nước ngoài.</> : <><b>Primary affiliation is read from recent publications.</b> Clarivate (Highly Cited Researchers) defines the primary affiliation as the institution where the researcher lives, holds a main position and does most of the work, <i>as reflected in recent publications</i>; honorary or fellowship affiliations do not count unless permanent residence and work are evident (Clarivate, 2023–2025). The recent factor therefore comes first: someone who recently moved to Vietnam is still ranked even if they published abroad years ago.</>}</li>
        <li>{vi ? <><b>Đa liên kết ngày càng phổ biến.</b> Tỉ lệ tác giả có nhiều liên kết cơ quan tăng từ khoảng 10% lên 16% kể từ 1996 (mẫu hơn 15 triệu tác giả, 40 quốc gia; Hottenrott, Rose &amp; Lawson, 2021), và tác giả đa liên kết thường có mặt trong các công trình tác động cao (Hottenrott &amp; Lawson, 2017). Một tên cơ quan xuất hiện trên bài báo chưa đủ để kết luận người đó làm việc chính ở cơ quan đó.</> : <><b>Multiple affiliations are increasingly common.</b> The share of authors with several institutional affiliations rose from about 10% to 16% since 1996 (over 15 million authors, 40 countries; Hottenrott, Rose &amp; Lawson, 2021), and multi-affiliated authors are more often found on high-impact papers (Hottenrott &amp; Lawson, 2017). An institution name on a paper alone does not show where someone mainly works.</>}</li>
        <li>{vi ? <><b>Liên kết phụ có thể được dùng để nâng thứ hạng cơ sở.</b> Bhattacharjee (2011) ghi nhận một số trường đại học thuê bán thời gian các nhà khoa học được trích dẫn nhiều với điều kiện ghi tên trường là cơ quan thứ hai; Bornmann &amp; Bauer (2015) phân tích hiện tượng này trong dữ liệu highlycited.com. Một bảng xếp hạng quốc gia không nên để liên kết phụ như vậy quyết định thứ hạng.</> : <><b>A secondary affiliation can be used to raise an institution’s rank.</b> Bhattacharjee (2011) reported universities hiring highly cited scientists part-time on condition that they list the university as a second affiliation; Bornmann &amp; Bauer (2015) analysed the phenomenon in highlycited.com data. A national table should not let such secondary affiliations decide ranks.</>}</li>
        <li>{vi ? <><b>Vì sao đo bằng tỉ lệ công trình, từng năm.</b> OpenAlex không có dữ liệu hợp đồng hay nơi làm việc chính, nhưng cơ quan ghi trên từng công trình kiểm chứng được. Lấy mức thấp nhất theo năm trong cửa sổ ba năm đòi hỏi liên kết Việt Nam phải <i>liên tục</i>, không chỉ xuất hiện ở một vài bài.</> : <><b>Why a per-year share of works.</b> OpenAlex has no contract or main-workplace data, but the affiliation printed on each work is verifiable. Taking the weakest year in the three-year window requires the Vietnam link to be <i>continuous</i>, not just present on a few papers.</>}</li>
      </ul>

      <h3>{vi ? "Cách chọn ngưỡng: hiệu chuẩn bằng dữ liệu thật, rồi hội đồng mô phỏng quyết định" : "How the thresholds are chosen: calibration on real data, then a simulated panel decides"}</h3>
      <p>{vi ? "Bước 1, đối chiếu độc lập. Với mẫu phân tầng các hồ sơ có ORCID, ProFind™ đọc công tác hiện tại do chính nhà khoa học khai trên ORCID (không ngày kết thúc hoặc kết thúc từ 2024): có nơi làm việc tại Việt Nam hay không. Từ đó ước lượng xác suất “hiện làm việc tại Việt Nam” theo từng mức tỉ lệ bằng hồi quy đơn điệu (Barlow và cộng sự, 1972). Hồ sơ ORCID không khai công tác hiện tại bị loại khỏi bước này." : "Step 1, independent check. For a stratified sample of profiles with an ORCID, ProFind™ reads the current employment declared by the scientists themselves on ORCID (no end date, or ending in 2024 or later): is there a workplace in Vietnam? From that it estimates the probability of “currently working in Vietnam” at each share level using monotone regression (Barlow et al., 1972). Profiles whose ORCID declares no current employment are left out of this step."}</p>
      <p>{vi ? "Bước 2, hội đồng mô phỏng, ba lần độc lập cho từng yếu tố. Mỗi “chuyên gia” mô phỏng có một lập trường (bao trùm, cân bằng hoặc chặt chẽ) và một mức coi trọng riêng giữa hai loại sai sót: loại nhầm người làm việc tại Việt Nam, hoặc đưa nhầm người không làm việc tại Việt Nam vào bảng. Mỗi người chọn ngưỡng làm tổn thất kỳ vọng nhỏ nhất theo xác suất ở bước 1, rồi cả hội đồng bàn bạc 3 vòng kiểu Delphi (Dalkey & Helmer, 1963): mỗi người biết trung vị của hội đồng và điều chỉnh một phần ý kiến về phía đó (French, 1956; DeGroot, 1974). Lần 1 có 1.000 chuyên gia; lần 2 có 500 chuyên gia với hạt giống khác; lần 3 có 100 chuyên gia thuộc 6 nhóm lĩnh vực, mỗi người cân nhắc trên hồ sơ của lĩnh vực mình." : "Step 2, the simulated panel, three independent runs per factor. Each simulated “expert” has a stance (inclusive, balanced or strict) and an own weighing of the two kinds of error: wrongly excluding someone who works in Vietnam, or wrongly admitting someone who does not. Each picks the threshold with the smallest expected loss under the step-1 probabilities, then the panel deliberates for 3 Delphi-style rounds (Dalkey & Helmer, 1963): each member sees the panel median and moves part of the way toward it (French, 1956; DeGroot, 1974). Run 1 has 1,000 experts; run 2 has 500 experts with another seed; run 3 has 100 experts from 6 fields, each weighing the profiles of their own field."}</p>
      <FactorBlock f={d.factors.recent} name={vi ? `Yếu tố gần đây (${yrs}): ngưỡng ${r}%` : `Recent factor (${yrs}): threshold ${r}%`} vi={vi} num={num} rule={rule} kind="recent" />
      <FactorBlock f={d.factors.overall} name={vi ? `Yếu tố dài hạn (hồ sơ chưa đủ công bố gần đây): ngưỡng ${t}%` : `Long-run factor (profiles with too few recent publications): threshold ${t}%`} vi={vi} num={num} rule={rule} kind="overall" />
      <h3>{vi ? "Quy tắc quyết định" : "Decision rule"}</h3>
      <p>{vi ? "Ngưỡng của mỗi yếu tố là trung vị của ba trung vị đồng thuận độc lập của hội đồng mô phỏng, làm tròn đến số nguyên; ProFind™ không thêm ràng buộc hay điều chỉnh nào khác. Dữ liệu cho thấy ở vùng giữa (khoảng 5% đến 95%) tỉ lệ làm việc tại Việt Nam tăng dần chứ không có ranh giới rõ, nên việc chọn ngưỡng ở vùng này là quyết định về giá trị; khoảng tin cậy rộng ở trên phản ánh đúng điều đó. Ngưỡng sẽ được xem xét lại khi có ý kiến chuyên gia thật." : "The threshold of each factor is the median of the three independent consensus medians of the simulated panel, rounded to an integer; ProFind™ adds no other constraint or adjustment. The data show that in the middle range (about 5% to 95%) the probability of working in Vietnam rises gradually with no clear boundary, so choosing a threshold there is a decision about values; the wide interval above reflects this. The thresholds will be revisited once real expert opinion is available."}</p>

      <h3>{vi ? "Lưu ý và giới hạn" : "Notes and limits"}</h3>
      <ul className="psp-ul">
        <li>{vi ? "Các hội đồng chuyên gia ở đây là MÔ PHỎNG, không phải ý kiến của người thật. Bằng chứng lấy từ dữ liệu thật (OpenAlex và ORCID); phần giả định là cơ cấu lập trường và mức đánh đổi giữa hai loại sai sót (hạt giống cố định, mã tại scripts/abroad-panel.mjs và scripts/abroad-decision.mjs, tái lập được)." : "The expert panels here are a SIMULATION, not real people’s opinions. Evidence comes from real data (OpenAlex and ORCID); the assumptions are the stance mix and the trade-off between the two kinds of error (fixed seeds, code in scripts/abroad-panel.mjs and scripts/abroad-decision.mjs, reproducible)."}</li>
        <li>{vi ? "Nhãn ORCID do nhà khoa học tự khai, có thể không cập nhật; “hiện làm việc tại Việt Nam” gồm cả người có thêm vị trí kiêm nhiệm tại Việt Nam. Mẫu hiệu chuẩn chỉ gồm hồ sơ có ORCID và có khai công tác hiện tại nên có thể lệch so với toàn bộ hồ sơ." : "ORCID labels are self-declared and may be out of date; “currently working in Vietnam” includes people holding an additional position in Vietnam. The calibration sample covers only profiles with an ORCID that declares current employment, so it may differ from all profiles."}</li>
        <li>{vi ? "Cơ quan ghi trên công trình phụ thuộc vào OpenAlex và có thể thiếu hoặc sai; công trình không có thông tin cơ quan không được tính. Năm hiện tại chưa kết thúc nên công bố của năm này còn ít." : "Affiliations printed on works depend on OpenAlex and may be missing or wrong; works without affiliation information are not counted. The current year is not over, so it has fewer publications."}</li>
      </ul>
      <h3>{vi ? "Tài liệu tham khảo" : "References"}</h3>
      <ul className="psp-ul psp-refs">{REFS.map((x) => <li key={x}>{x}</li>)}</ul>
    </section>
  );
}
