// Mục "Phạm vi Việt Nam: quy tắc liên kết chính" của trang PRO-SCORE1000: quy tắc, cơ sở khoa học, cách chọn ngưỡng (có mô phỏng hội đồng). Số liệu lấy từ public/data/abroad-panel.json (scripts/abroad-panel.mjs).
// Bản chữ tĩnh cho công cụ tìm kiếm nằm trong scripts/build-seo-pages.mjs (/pro-score/): sửa một nơi thì sửa cả hai.
import { useEffect, useState } from "react";
import type { Lang } from "./i18n";

type Round = { round: number; label: string; median: number; p25: number; p75: number };
type Stance = { id: string; vi: string; n: number; median: number; p25: number; p75: number };
export type AbroadPanel = { built: string; seed: number; n: number; rounds: number; profiles: number; mixture: { piVn: number; bayesEqualCostThreshold: number }; stances: Stance[]; rounds_: Round[]; consensus: { median: number; p25: number; p75: number }; hist: number[]; sens: { t: number; n: number }[]; curve: { t: number; excluded: number; admitted: number; tagged: number }[]; impliedCostRatio: { t: number; kFrom: number; kTo: number }[] };
type RunSum = { run: number; n: number; seed: number; fields: boolean; median: number; p25: number; p75: number };
type FieldRow = { id: string; vi: string; experts: number; profiles: number; bayesEqualCost: number; initialMedian: number; p25: number; p75: number };
export type AbroadDecision = { alpha: number; vnClusterExpected: number; reference: { R: number; from: RunSum[] }; constraint: { C: number; allowedWronglyExcluded: number }; threshold: number; atThreshold: { t: number; expectedWronglyExcluded: number; expectedWronglyAdmitted: number; tagged: number | null }; atPrevious: { t: number; expectedWronglyExcluded: number; expectedWronglyAdmitted: number; tagged: number | null }; alphaSensitivity: { alpha: number; C: number; threshold: number }[]; verification: { bootstrap: { resamples: number; bayesEqualCost: { median: number; lo95: number; hi95: number }; panelConsensus: { median: number; lo95: number; hi95: number } }; mixes: { label: string; median: number }[] } | null; fields: FieldRow[] | null };
const STANCE_EN: Record<string, string> = { inclusive: "Inclusive (avoid missing Vietnamese scientists abroad and multi-affiliated scientists)", balanced: "Balanced (both kinds of error weigh the same)", strict: "Strict (prefer a table of people whose primary affiliation is in Vietnam)" };
export const REFS: string[] = [
  "Bhattacharjee, Y. (2011). Saudi universities offer cash in exchange for academic prestige. Science, 334(6061), 1344–1345.",
  "Bornmann, L., & Bauer, J. (2015). Which of the world’s institutions employ the most highly cited researchers? An analysis of the data from highlycited.com. Journal of the Association for Information Science and Technology (arXiv:1407.2037).",
  "Clarivate (2023–2025). Highly Cited Researchers: methodology, FAQs and statement on researcher affiliations (clarivate.com/highly-cited-researchers).",
  "Dalkey, N., & Helmer, O. (1963). An experimental application of the Delphi method to the use of experts. Management Science, 9(3), 458–467.",
  "DeGroot, M. H. (1974). Reaching a consensus. Journal of the American Statistical Association, 69(345), 118–121.",
  "Dempster, A. P., Laird, N. M., & Rubin, D. B. (1977). Maximum likelihood from incomplete data via the EM algorithm. Journal of the Royal Statistical Society B, 39(1), 1–38.",
  "French, J. R. P. (1956). A formal theory of social power. Psychological Review, 63(3), 181–194.",
  "Hottenrott, H., & Lawson, C. (2017). A first look at multiple institutional affiliations: a study of authors in Germany, Japan and the UK. Scientometrics, 111(1), 285–295. doi:10.1007/s11192-017-2257-6",
  "Hottenrott, H., Rose, M. E., & Lawson, C. (2021). The rise of multiple institutional affiliations in academia. Journal of the Association for Information Science and Technology.",
  "Neyman, J., & Pearson, E. S. (1933). On the problem of the most efficient tests of statistical hypotheses. Philosophical Transactions of the Royal Society A, 231, 289–337.",
];
export function AbroadRule({ lang, num }: { lang: Lang; num: (n: number, d?: number) => string }) {
  const vi = lang === "vi";
  const [p, setP] = useState<AbroadPanel | null>(null), [d, setD] = useState<AbroadDecision | null>(null);
  useEffect(() => { fetch("./data/abroad-panel.json").then((r) => r.json()).then(setP).catch(() => {}); fetch("./data/abroad-decision.json").then((r) => r.json()).then(setD).catch(() => {}); }, []);
  if (!p || !d) return null;
  const pol = d.threshold, hmax = Math.max(...p.hist), R = d.reference.R, C = d.constraint.C, al = d.alpha * 100;
  const stanceName = (s: Stance) => (vi ? s.vi : STANCE_EN[s.id]);
  return (
    <section className="psp-sec" id="pham-vi-viet-nam"><h2>{vi ? "Phạm vi Việt Nam: quy tắc “liên kết chính”" : "Vietnam scope: the “primary affiliation” rule"}</h2>
      <p>{vi ? "ProFind là bảng tra cứu và xếp hạng dành riêng cho nhà khoa học của các trường, viện Việt Nam. Để PRO-SCORE1000 phản ánh đóng góp cho cộng đồng khoa học Việt Nam, một hồ sơ chỉ được xếp hạng khi liên kết chính của người đó ở Việt Nam." : "ProFind is a lookup and ranking table dedicated to scientists of Vietnamese universities and institutes. So that PRO-SCORE1000 reflects contribution to the Vietnamese scientific community, a profile is ranked only when the person’s primary affiliation is in Vietnam."}</p>
      <aside className="psp-disc" role="note"><div>
        <b>{vi ? "Quy tắc" : "The rule"}</b>
        <p>{vi ? `Hồ sơ có dưới ${pol}% công trình mang liên kết cơ quan tại Việt Nam (tính trên các công trình mà OpenAlex ghi cơ quan, cần tối thiểu 15 công trình như vậy) được gắn nhãn “Liên kết chính ở nước ngoài” và không xếp hạng. Hồ sơ vẫn hiển thị trên ProFind.` : `A profile with under ${pol}% of its works carrying an affiliation in Vietnam (counted over works with an affiliation recorded in OpenAlex, at least 15 such works) is tagged “Primary affiliation abroad” and not ranked. The profile stays visible on ProFind.`}</p>
        <p>{vi ? "Không áp dụng cho: hồ sơ chưa đủ dữ liệu cơ quan; hồ sơ trong danh sách Top 2% mục Việt Nam của Elsevier; hồ sơ được quản trị viên xác nhận là ngoại lệ (danh sách công khai trong mã nguồn, tệp data/vn-confirmed.json). Chủ hồ sơ có thể gửi đính chính." : "Not applied to: profiles with too little affiliation data; profiles in Elsevier’s Top 2% list under Vietnam; profiles confirmed as exceptions by an administrator (public list in the source code, data/vn-confirmed.json). Profile owners may submit a correction."}</p>
        <p>{vi ? "Giới hạn này chỉ dành cho bảng Việt Nam. Nếu sau này ProFind mở rộng sang bảng phạm vi thế giới, bảng đó sẽ không có giới hạn này." : "This limit applies to the Vietnam table only. If ProFind later adds a worldwide table, that table will not have this limit."}</p>
      </div></aside>

      <h3>{vi ? "Cơ sở khoa học" : "Scientific basis"}</h3>
      <ul className="psp-ul">
        <li>{vi ? <><b>Đa liên kết ngày càng phổ biến.</b> Tỉ lệ tác giả có nhiều liên kết cơ quan tăng từ khoảng 10% lên 16% kể từ 1996 (mẫu hơn 15 triệu tác giả, 40 quốc gia; Hottenrott, Rose &amp; Lawson, 2021), và tác giả đa liên kết thường có mặt trong các công trình tác động cao (Hottenrott &amp; Lawson, 2017). Vì vậy một tên cơ quan xuất hiện trên bài báo chưa đủ để kết luận người đó làm việc chính ở cơ quan đó.</> : <><b>Multiple affiliations are increasingly common.</b> The share of authors with several institutional affiliations rose from about 10% to 16% since 1996 (over 15 million authors, 40 countries; Hottenrott, Rose &amp; Lawson, 2021), and multi-affiliated authors are more often found on high-impact papers (Hottenrott &amp; Lawson, 2017). An institution name on a paper alone therefore does not show where someone mainly works.</>}</li>
        <li>{vi ? <><b>Liên kết phụ có thể được dùng để nâng thứ hạng cơ sở.</b> Bhattacharjee (2011) ghi nhận một số trường đại học thuê bán thời gian các nhà khoa học được trích dẫn nhiều với điều kiện ghi tên trường là cơ quan thứ hai; Bornmann &amp; Bauer (2015) phân tích hiện tượng này trong dữ liệu highlycited.com. Một bảng xếp hạng quốc gia không nên để liên kết phụ như vậy quyết định thứ hạng.</> : <><b>A secondary affiliation can be used to raise an institution’s rank.</b> Bhattacharjee (2011) reported universities hiring highly cited scientists part-time on condition that they list the university as a second affiliation; Bornmann &amp; Bauer (2015) analysed the phenomenon in highlycited.com data. A national table should not let such secondary affiliations decide ranks.</>}</li>
        <li>{vi ? <><b>Các tổ chức xếp hạng đã chuyển sang “liên kết chính”.</b> Clarivate (Highly Cited Researchers) định nghĩa liên kết chính là cơ quan nơi nhà nghiên cứu sinh sống, giữ vị trí chính và thực hiện phần lớn công việc, thể hiện qua công bố gần đây; liên kết danh dự hoặc nghiên cứu viên không được coi là liên kết chính nếu không chứng minh được làm việc thường trực (Clarivate, 2023–2025).</> : <><b>Ranking organisations moved to “primary affiliation”.</b> Clarivate (Highly Cited Researchers) defines the primary affiliation as the institution where the researcher lives, holds a main position and does most of the work, as reflected in recent publications; honorary or fellowship affiliations do not count unless permanent residence and work are evident (Clarivate, 2023–2025).</>}</li>
        <li>{vi ? <><b>Vì sao đo bằng tỉ lệ công trình.</b> OpenAlex không có dữ liệu hợp đồng hay nơi làm việc chính, nhưng cơ quan ghi trên từng công trình kiểm chứng được và bao trùm cả sự nghiệp. Tỉ lệ công trình mang liên kết Việt Nam là một xấp xỉ của “phần lớn công việc” trong định nghĩa trên.</> : <><b>Why measure by share of works.</b> OpenAlex has no contract or main-workplace data, but the affiliation printed on each work is verifiable and spans the whole career. The share of works with a Vietnamese affiliation approximates the “majority of work” in the definition above.</>}</li>
      </ul>

      <h3>{vi ? "Cách chọn ngưỡng" : "How the threshold is chosen"}</h3>
      <p>{vi ? `Bước 1, dữ liệu. Với ${num(p.profiles)} hồ sơ đủ dữ liệu cơ quan, phân bố “% công trình có liên kết tại Việt Nam” có hai cụm rõ: một cụm gần 0% (liên kết chính ở nước ngoài) và một cụm gần 100%, vùng giữa thưa hơn hẳn. Mô hình trộn hai phân phối Beta (thuật toán EM; Dempster, Laird & Rubin, 1977) cho thấy khoảng ${num(p.mixture.piVn * 100)}% hồ sơ thuộc cụm Việt Nam.` : `Step 1, the data. Across ${num(p.profiles)} profiles with enough affiliation data, the distribution of “% of works with an affiliation in Vietnam” has two clear clusters: one near 0% (primary affiliation abroad) and one near 100%, with a much sparser middle. A two-component Beta mixture (EM algorithm; Dempster, Laird & Rubin, 1977) puts about ${num(p.mixture.piVn * 100)}% of profiles in the Vietnam cluster.`}</p>
      <div className="abh" role="img" aria-label={vi ? "Phân bố số hồ sơ theo % công trình có liên kết Việt Nam" : "Profiles by % of works with a Vietnam affiliation"}>{p.hist.map((v, i) => <i key={i} title={`${i * 5}–${i * 5 + 5}%: ${num(v)}`} style={{ height: `${Math.max(2, Math.round((v / hmax) * 100))}%` }} className={i * 5 < pol ? "lo" : undefined} />)}</div>
      <p className="meta">{vi ? `Trục ngang: 0% đến 100%, mỗi cột 5%; cột đậm là vùng dưới ngưỡng ${pol}%.` : `Horizontal axis: 0% to 100%, 5% per bar; darker bars lie below the ${pol}% threshold.`}</p>
      <p>{vi ? `Bước 2, hội đồng mô phỏng, ba lần độc lập. Mỗi "chuyên gia" mô phỏng có một lập trường (bao trùm, cân bằng hoặc chặt chẽ) và một mức coi trọng riêng giữa hai loại sai sót: loại nhầm người làm việc tại Việt Nam, hoặc đưa nhầm người có liên kết chính ở nước ngoài vào bảng. Mỗi người chọn ngưỡng làm tổn thất kỳ vọng nhỏ nhất theo mô hình ở bước 1, rồi cả hội đồng bàn bạc ${p.rounds} vòng kiểu Delphi (Dalkey & Helmer, 1963): mỗi người biết trung vị của hội đồng và điều chỉnh một phần ý kiến về phía đó (mô hình đồng thuận của French, 1956 và DeGroot, 1974). Lần 1 có ${num(d.reference.from[0].n)} chuyên gia; lần 2 có ${num(d.reference.from[1].n)} chuyên gia với hạt giống khác; lần 3 có ${num(d.reference.from[2].n)} chuyên gia thuộc 6 nhóm lĩnh vực, mỗi người cân nhắc trên hồ sơ của lĩnh vực mình.` : `Step 2, the simulated panel, three independent runs. Each simulated “expert” has a stance (inclusive, balanced or strict) and an own weighing of the two kinds of error: wrongly excluding someone who works in Vietnam, or wrongly admitting someone whose primary affiliation is abroad. Each picks the threshold with the smallest expected loss under the step-1 model, then the panel deliberates for ${p.rounds} Delphi-style rounds (Dalkey & Helmer, 1963): each member sees the panel median and moves part of the way toward it (consensus models of French, 1956 and DeGroot, 1974). Run 1 has ${num(d.reference.from[0].n)} experts; run 2 has ${num(d.reference.from[1].n)} experts with another seed; run 3 has ${num(d.reference.from[2].n)} experts from 6 fields, each weighing the profiles of their own field.`}</p>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Lần mô phỏng" : "Run"}</th><th>{vi ? "Số chuyên gia" : "Experts"}</th><th>{vi ? "Hạt giống" : "Seed"}</th><th>{vi ? "Trung vị đồng thuận (%)" : "Consensus median (%)"}</th><th>{vi ? "Tứ phân vị (%)" : "Interquartile (%)"}</th></tr></thead>
        <tbody>{d.reference.from.map((r) => <tr key={r.run}><td>{vi ? `Lần ${r.run}${r.fields ? " (nhiều lĩnh vực)" : ""}` : `Run ${r.run}${r.fields ? " (multi-field)" : ""}`}</td><td>{num(r.n)}</td><td>{r.seed}</td><td>{num(r.median, 1)}</td><td>{num(r.p25, 1)} – {num(r.p75, 1)}</td></tr>)}</tbody></table></div>
      <p>{vi ? "Lần 1 theo ba lập trường:" : "Run 1 by stance:"} {p.stances.map((x) => `${stanceName(x)}: ${num(x.median, 1)}%`).join("; ")}.</p>
      {d.verification && <p>{vi ? `Kiểm định lại (lần 2): bootstrap ${d.verification.bootstrap.resamples} lần trên các hồ sơ cho khoảng tin cậy 95% của ngưỡng tối ưu là ${d.verification.bootstrap.bayesEqualCost.lo95}–${d.verification.bootstrap.bayesEqualCost.hi95}% và của trung vị hội đồng là ${d.verification.bootstrap.panelConsensus.lo95}–${d.verification.bootstrap.panelConsensus.hi95}%; đổi cơ cấu lập trường cho kết quả từ ${Math.min(...d.verification.mixes.map((m) => m.median))}% (toàn bao trùm) đến ${Math.max(...d.verification.mixes.map((m) => m.median))}% (toàn chặt chẽ).` : `Re-check (run 2): ${d.verification.bootstrap.resamples} bootstrap resamples of the profiles give a 95% interval of ${d.verification.bootstrap.bayesEqualCost.lo95}–${d.verification.bootstrap.bayesEqualCost.hi95}% for the optimal threshold and ${d.verification.bootstrap.panelConsensus.lo95}–${d.verification.bootstrap.panelConsensus.hi95}% for the panel median; changing the stance mix gives from ${Math.min(...d.verification.mixes.map((m) => m.median))}% (all inclusive) to ${Math.max(...d.verification.mixes.map((m) => m.median))}% (all strict).`}</p>}
      {d.fields && <><div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Nhóm lĩnh vực (lần 3)" : "Field group (run 3)"}</th><th>{vi ? "Hồ sơ có dữ liệu" : "Profiles with data"}</th><th>{vi ? "Chuyên gia" : "Experts"}</th><th>{vi ? "Ngưỡng tối ưu, hai sai sót nặng như nhau (%)" : "Optimal threshold, equal errors (%)"}</th></tr></thead>
        <tbody>{d.fields.map((f) => <tr key={f.id}><td>{f.vi}</td><td>{num(f.profiles)}</td><td>{f.experts}</td><td>{f.profiles < 100 ? (vi ? "chưa đủ dữ liệu để ước lượng" : "too little data to estimate") : num(f.bayesEqualCost)}</td></tr>)}</tbody></table></div>
        <p className="meta">{vi ? "Các lĩnh vực có đủ dữ liệu cho ngưỡng tối ưu gần như trùng nhau (44–45%), nên một ngưỡng chung cho cả nước là chấp nhận được. Nhân văn, nghệ thuật có rất ít hồ sơ đủ dữ liệu cơ quan trong OpenAlex nên chưa ước lượng được; quy tắc hầu như không áp dụng cho nhóm này." : "Fields with enough data give almost identical optimal thresholds (44–45%), so one national threshold is acceptable. Humanities and arts have very few profiles with enough affiliation data in OpenAlex, so no estimate is possible; the rule rarely applies to that group."}</p></>}

      <h3>{vi ? "Quy tắc quyết định" : "Decision rule"}</h3>
      <p>{vi ? `Kết quả mô phỏng cho ta một mức tham chiếu, nhưng chọn ngưỡng còn là quyết định về giá trị. Vì vậy ProFind áp dụng một quy tắc đặt trước, gồm ba bước:` : `The simulations give a reference level, but choosing a threshold is also a decision about values. ProFind therefore applies a rule set in advance, in three steps:`}</p>
      <ol className="psp-ul">
        <li>{vi ? <><b>Mức tham chiếu R = {num(R)}%</b>: trung vị của ba trung vị đồng thuận độc lập ở trên.</> : <><b>Reference R = {num(R)}%</b>: the median of the three independent consensus medians above.</>}</li>
        <li>{vi ? <><b>Ràng buộc thận trọng C = {num(C)}%</b>: kiểm soát sai sót loại I (Neyman &amp; Pearson, 1933), tức nguyên tắc “không loại nhầm”. C là ngưỡng cao nhất mà số hồ sơ thuộc cụm Việt Nam bị loại nhầm kỳ vọng không vượt {num(al, 1)}% số hồ sơ kỳ vọng thuộc cụm này (≈ {num(d.constraint.allowedWronglyExcluded)} trên {num(d.vnClusterExpected)}). Mức {num(al, 1)}% là phán đoán của ProFind: một hồ sơ bị loại nhầm thiệt hại nặng hơn nhiều so với một hồ sơ được đưa nhầm vào bảng.</> : <><b>Precautionary constraint C = {num(C)}%</b>: control of the type-I error (Neyman &amp; Pearson, 1933), i.e. a “do not wrongly exclude” principle. C is the highest threshold at which the expected number of wrongly excluded profiles from the Vietnam cluster stays within {num(al, 1)}% of the expected size of that cluster (≈ {num(d.constraint.allowedWronglyExcluded)} of {num(d.vnClusterExpected)}). The {num(al, 1)}% level is ProFind’s judgment: a wrongly excluded profile does more harm than a wrongly admitted one.</>}</li>
        <li>{vi ? <><b>Ngưỡng áp dụng = {pol}%</b>: lấy giá trị nhỏ hơn giữa R và C, làm tròn xuống bội số của 5, nên không bao giờ cao hơn mức đồng thuận và không vượt ràng buộc thận trọng.</> : <><b>Threshold in force = {pol}%</b>: the smaller of R and C, rounded down to a multiple of 5, so it never exceeds the consensus level or the precautionary constraint.</>}</li>
      </ol>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Ngưỡng" : "Threshold"}</th><th>{vi ? "Hồ sơ bị gắn nhãn" : "Profiles tagged"}</th><th>{vi ? "Loại nhầm (kỳ vọng)" : "Wrongly excluded (expected)"}</th><th>{vi ? "Đưa nhầm (kỳ vọng)" : "Wrongly admitted (expected)"}</th></tr></thead>
        <tbody><tr className="all"><td>{vi ? `Đang áp dụng: ${pol}%` : `In force: ${pol}%`}</td><td>{num(d.atThreshold.tagged ?? 0)}</td><td>{num(d.atThreshold.expectedWronglyExcluded)}</td><td>{num(d.atThreshold.expectedWronglyAdmitted)}</td></tr>
          <tr><td>{vi ? `Ngưỡng ban đầu: ${d.atPrevious.t}%` : `Initial threshold: ${d.atPrevious.t}%`}</td><td>{num(d.atPrevious.tagged ?? 0)}</td><td>{num(d.atPrevious.expectedWronglyExcluded)}</td><td>{num(d.atPrevious.expectedWronglyAdmitted)}</td></tr>
          {p.curve.filter((x) => x.t === R).map((x) => <tr key={x.t}><td>{vi ? `Mức tham chiếu: ${x.t}%` : `Reference: ${x.t}%`}</td><td>{num(x.tagged)}</td><td>{num(x.excluded)}</td><td>{num(x.admitted)}</td></tr>)}</tbody></table></div>
      <p className="meta">{vi ? `Độ nhạy theo mức α của ràng buộc thận trọng: ${d.alphaSensitivity.map((x) => `α = ${num(x.alpha * 100, 1)}% cho ngưỡng ${x.threshold}%`).join("; ")}. Ngưỡng ${pol}% nghĩa là chấp nhận việc loại nhầm một người làm việc tại Việt Nam nặng gấp khoảng ${p.impliedCostRatio.find((x) => x.t === pol) ? `${num(p.impliedCostRatio.find((x) => x.t === pol)!.kFrom, 1)}–${num(p.impliedCostRatio.find((x) => x.t === pol)!.kTo, 1)}` : "?"} lần việc đưa nhầm một người có liên kết chính ở nước ngoài.` : `Sensitivity to the α level of the precautionary constraint: ${d.alphaSensitivity.map((x) => `α = ${num(x.alpha * 100, 1)}% gives a ${x.threshold}% threshold`).join("; ")}. A ${pol}% threshold means treating the wrongful exclusion of someone who works in Vietnam as about ${p.impliedCostRatio.find((x) => x.t === pol) ? `${num(p.impliedCostRatio.find((x) => x.t === pol)!.kFrom, 1)}–${num(p.impliedCostRatio.find((x) => x.t === pol)!.kTo, 1)}` : "?"} times as serious as wrongly admitting someone whose primary affiliation is abroad.`}</p>
      <p>{vi ? `Kết luận. Ngưỡng ${pol}% thấp hơn mức đồng thuận ${num(R)}% có chủ ý: ProFind ưu tiên không loại nhầm người làm việc tại Việt Nam; cái giá là một số hồ sơ có liên kết chính ở nước ngoài vẫn có thể được xếp hạng (xem bảng sai sót kỳ vọng). Ngưỡng sẽ được xem xét lại khi có ý kiến chuyên gia thật.` : `Conclusion. The ${pol}% threshold is deliberately below the ${num(R)}% consensus level: ProFind prefers not to wrongly exclude people who work in Vietnam, at the cost that some profiles with a primary affiliation abroad may still be ranked (see the expected-error table). The threshold will be revisited once real expert opinion is available.`}</p>
      <h3>{vi ? "Lưu ý và giới hạn" : "Notes and limits"}</h3>
      <ul className="psp-ul">
        <li>{vi ? `Các hội đồng chuyên gia ở đây là MÔ PHỎNG, không phải ý kiến của người thật. Bằng chứng lấy từ dữ liệu thật ở bước 1; phần giả định là cơ cấu lập trường và mức đánh đổi giữa hai loại sai sót (hạt giống cố định, mã tại scripts/abroad-panel.mjs và scripts/abroad-decision.mjs, tái lập được).` : `The expert panels here are a SIMULATION, not real people’s opinions. Evidence comes from real data in step 1; the assumptions are the stance mix and the trade-off between the two kinds of error (fixed seeds, code in scripts/abroad-panel.mjs and scripts/abroad-decision.mjs, reproducible).`}</li>
        <li>{vi ? "Mô hình hai cụm là giả định; người mới chuyển về làm việc tại Việt Nam sau nhiều năm công bố ở nước ngoài, và người Việt công tác ở nước ngoài, có thể nằm ở vùng giữa hoặc vùng thấp. Do đó quy tắc có ngoại lệ do quản trị viên xác nhận và cho phép chủ hồ sơ gửi đính chính." : "The two-cluster model is an assumption; people who recently moved to work in Vietnam after many years of publishing abroad, and Vietnamese scientists working abroad, may fall in the middle or low range. Hence the rule has administrator-confirmed exceptions and lets profile owners submit corrections."}</li>
        <li>{vi ? "Cơ quan ghi trên công trình phụ thuộc vào OpenAlex và có thể thiếu hoặc sai; công trình không có thông tin cơ quan không được tính." : "Affiliations printed on works depend on OpenAlex and may be missing or wrong; works without affiliation information are not counted."}</li>
      </ul>
      <h3>{vi ? "Tài liệu tham khảo" : "References"}</h3>
      <ul className="psp-ul psp-refs">{REFS.map((r) => <li key={r}>{r}</li>)}</ul>
    </section>
  );
}
