// Mục "Phạm vi Việt Nam: quy tắc liên kết chính" của trang PRO-SCORE1000: quy tắc, cơ sở khoa học, cách chọn ngưỡng (có mô phỏng hội đồng). Số liệu lấy từ public/data/abroad-panel.json (scripts/abroad-panel.mjs).
// Bản chữ tĩnh cho công cụ tìm kiếm nằm trong scripts/build-seo-pages.mjs (/pro-score/): sửa một nơi thì sửa cả hai.
import { useEffect, useState } from "react";
import type { Lang } from "./i18n";

type Round = { round: number; label: string; median: number; p25: number; p75: number };
type Stance = { id: string; vi: string; n: number; median: number; p25: number; p75: number };
export type AbroadPanel = { built: string; seed: number; n: number; rounds: number; profiles: number; mixture: { piVn: number; bayesEqualCostThreshold: number }; stances: Stance[]; rounds_: Round[]; consensus: { median: number; p25: number; p75: number }; policy: number; errorsAtPolicy: { t: number; expectedWronglyExcluded: number; expectedWronglyIncluded: number }; errorsAtConsensus: { t: number; expectedWronglyExcluded: number; expectedWronglyIncluded: number }; hist: number[]; sens: { t: number; n: number }[] };
const STANCE_EN: Record<string, string> = { inclusive: "Inclusive (avoid missing Vietnamese scientists abroad and multi-affiliated scientists)", balanced: "Balanced (both kinds of error weigh the same)", strict: "Strict (prefer a table of people whose primary affiliation is in Vietnam)" };
export const REFS: string[] = [
  "Bhattacharjee, Y. (2011). Saudi universities offer cash in exchange for academic prestige. Science, 334(6061), 1344–1345.",
  "Bornmann, L., & Bauer, J. (2015). Which of the world’s institutions employ the most highly cited researchers? An analysis of the data from highlycited.com. Journal of the Association for Information Science and Technology (arXiv:1407.2037).",
  "Clarivate (2023–2025). Highly Cited Researchers: methodology, FAQs and statement on researcher affiliations (clarivate.com/highly-cited-researchers).",
  "Dalkey, N., & Helmer, O. (1963). An experimental application of the Delphi method to the use of experts. Management Science, 9(3), 458–467.",
  "DeGroot, M. H. (1974). Reaching a consensus. Journal of the American Statistical Association, 69(345), 118–121.",
  "Dempster, A. P., Laird, N. M., & Rubin, D. B. (1977). Maximum likelihood from incomplete data via the EM algorithm. Journal of the Royal Statistical Society B, 39(1), 1–38.",
  "French, J. R. P. (1956). A formal theory of social power. Psychological Review, 63(3), 181–194.",
  "Hottenrott, H., & Lawson, C. (2017). A first look at multiple institutional affiliations: a study of authors in Germany, Japan and the UK. Scientometrics, 111(1), 285–295. doi:10.1007/s11192-017-2257-6",
  "Hottenrott, H., Rose, M. E., & Lawson, C. (2021). The rise of multiple institutional affiliations in academia. Journal of the Association for Information Science and Technology.",
];
export function AbroadRule({ lang, num }: { lang: Lang; num: (n: number, d?: number) => string }) {
  const vi = lang === "vi";
  const [p, setP] = useState<AbroadPanel | null>(null);
  useEffect(() => { fetch("./data/abroad-panel.json").then((r) => r.json()).then(setP).catch(() => {}); }, []);
  if (!p) return null;
  const pol = p.policy, c = p.consensus, last = p.rounds_[p.rounds_.length - 1], hmax = Math.max(...p.hist);
  const rel = pol < c.p25 ? (vi ? "thấp hơn" : "lower than") : pol > c.p75 ? (vi ? "cao hơn" : "higher than") : (vi ? "nằm trong khoảng" : "within the range of");
  const stanceName = (s: Stance) => (vi ? s.vi : STANCE_EN[s.id]);
  return (
    <section className="psp-sec" id="pham-vi-viet-nam"><h2>{vi ? "Phạm vi Việt Nam: quy tắc “liên kết chính”" : "Vietnam scope: the “primary affiliation” rule"}</h2>
      <p>{vi ? "ProFind là bảng tra cứu và xếp hạng dành riêng cho nhà khoa học của các trường, viện Việt Nam. Để PRO-SCORE1000 phản ánh đóng góp cho cộng đồng khoa học Việt Nam, một hồ sơ chỉ được xếp hạng khi liên kết chính của người đó ở Việt Nam." : "ProFind is a lookup and ranking table dedicated to scientists of Vietnamese universities and institutes. So that PRO-SCORE1000 reflects contribution to the Vietnamese scientific community, a profile is ranked only when the person’s primary affiliation is in Vietnam."}</p>
      <aside className="psp-disc" role="note"><div>
        <b>{vi ? "Quy tắc" : "The rule"}</b>
        <p>{vi ? `Hồ sơ có dưới ${pol}% công trình mang liên kết cơ quan tại Việt Nam (tính trên các công trình mà OpenAlex ghi cơ quan, cần tối thiểu 15 công trình như vậy) được gắn nhãn “Liên kết chính ở nước ngoài” và không xếp hạng. Hồ sơ vẫn hiển thị trên ProFind.` : `A profile with under ${pol}% of its works carrying an affiliation in Vietnam (counted over works with an affiliation recorded in OpenAlex, at least 15 such works) is tagged “Primary affiliation abroad” and not ranked. The profile stays visible on ProFind.`}</p>
        <p>{vi ? "Không áp dụng cho: hồ sơ chưa đủ dữ liệu cơ quan; hồ sơ trong danh sách Top 2% mục Việt Nam của Elsevier; hồ sơ được quản trị viên xác nhận là ngoại lệ (danh sách công khai trong mã nguồn, tệp data/vn-confirmed.json). Chủ hồ sơ có thể gửi đính chính." : "Not applied to: profiles with too little affiliation data; profiles in Elsevier’s Top 2% list under Vietnam; profiles confirmed as exceptions by an administrator (public list in the source code, data/vn-confirmed.json). Profile owners may submit a correction."}</p>
        <p>{vi ? "Giới hạn này chỉ dành cho bảng Việt Nam. Nếu sau này ProFind mở rộng sang bảng phạm vi thế giới, bảng đó sẽ không có giới hạn này." : "This limit applies to the Vietnam table only. If ProFind later adds a worldwide table, that table will not have this limit."}</p>
      </div></aside>

      <h3>{vi ? "Cơ sở khoa học" : "Scientific basis"}</h3>
      <ul className="psp-ul">
        <li>{vi ? <><b>Đa liên kết ngày càng phổ biến.</b> Tỉ lệ tác giả có nhiều liên kết cơ quan tăng từ khoảng 10% lên 16% kể từ 1996 (mẫu hơn 15 triệu tác giả, 40 quốc gia; Hottenrott, Rose &amp; Lawson, 2021), và tác giả đa liên kết thường có mặt trong các công trình tác động cao (Hottenrott &amp; Lawson, 2017). Vì vậy một tên cơ quan xuất hiện trên bài báo chưa đủ để kết luận người đó làm việc chính ở cơ quan đó.</> : <><b>Multiple affiliations are increasingly common.</b> The share of authors with several institutional affiliations rose from about 10% to 16% since 1996 (over 15 million authors, 40 countries; Hottenrott, Rose &amp; Lawson, 2021), and multi-affiliated authors are more often found on high-impact papers (Hottenrott &amp; Lawson, 2017). An institution name on a paper alone therefore does not show where someone mainly works.</>}</li>
        <li>{vi ? <><b>Liên kết phụ có thể được dùng để nâng thứ hạng cơ sở.</b> Bhattacharjee (2011) ghi nhận một số trường đại học thuê bán thời gian các nhà khoa học được trích dẫn nhiều với điều kiện ghi tên trường là cơ quan thứ hai; Bornmann &amp; Bauer (2015) phân tích hiện tượng này trong dữ liệu highlycited.com. Một bảng xếp hạng quốc gia không nên để liên kết phụ như vậy quyết định thứ hạng.</> : <><b>A secondary affiliation can be used to raise an institution’s rank.</b> Bhattacharjee (2011) reported universities hiring highly cited scientists part-time on condition that they list the university as a second affiliation; Bornmann &amp; Bauer (2015) analysed the phenomenon in highlycited.com data. A national table should not let such secondary affiliations decide ranks.</>}</li>
        <li>{vi ? <><b>Các tổ chức xếp hạng đã chuyển sang “liên kết chính”.</b> Clarivate (Highly Cited Researchers) định nghĩa liên kết chính là cơ quan nơi nhà nghiên cứu sinh sống, giữ vị trí chính và thực hiện phần lớn công việc, thể hiện qua công bố gần đây; liên kết danh dự hoặc nghiên cứu viên không được coi là liên kết chính nếu không chứng minh được làm việc thường trực (Clarivate, 2023–2025).</> : <><b>Ranking organisations moved to “primary affiliation”.</b> Clarivate (Highly Cited Researchers) defines the primary affiliation as the institution where the researcher lives, holds a main position and does most of the work, as reflected in recent publications; honorary or fellowship affiliations do not count unless permanent residence and work are evident (Clarivate, 2023–2025).</>}</li>
        <li>{vi ? <><b>Vì sao đo bằng tỉ lệ công trình.</b> OpenAlex không có dữ liệu hợp đồng hay nơi làm việc chính, nhưng cơ quan ghi trên từng công trình kiểm chứng được và bao trùm cả sự nghiệp. Tỉ lệ công trình mang liên kết Việt Nam là một xấp xỉ của “phần lớn công việc” trong định nghĩa trên.</> : <><b>Why measure by share of works.</b> OpenAlex has no contract or main-workplace data, but the affiliation printed on each work is verifiable and spans the whole career. The share of works with a Vietnamese affiliation approximates the “majority of work” in the definition above.</>}</li>
      </ul>

      <h3>{vi ? "Cách chọn ngưỡng" : "How the threshold is chosen"}</h3>
      <p>{vi ? `Bước 1, dữ liệu. Với ${num(p.profiles)} hồ sơ đủ dữ liệu cơ quan, phân bố “% công trình có liên kết tại Việt Nam” có hai cụm rõ: một cụm gần 0% (liên kết chính ở nước ngoài) và một cụm gần 100%, vùng giữa thưa hơn hẳn. Mô hình trộn hai phân phối Beta (thuật toán EM; Dempster, Laird & Rubin, 1977) cho thấy khoảng ${num(p.mixture.piVn * 100)}% hồ sơ thuộc cụm Việt Nam.` : `Step 1, the data. Across ${num(p.profiles)} profiles with enough affiliation data, the distribution of “% of works with an affiliation in Vietnam” has two clear clusters: one near 0% (primary affiliation abroad) and one near 100%, with a much sparser middle. A two-component Beta mixture (EM algorithm; Dempster, Laird & Rubin, 1977) puts about ${num(p.mixture.piVn * 100)}% of profiles in the Vietnam cluster.`}</p>
      <div className="abh" role="img" aria-label={vi ? "Phân bố số hồ sơ theo % công trình có liên kết Việt Nam" : "Profiles by % of works with a Vietnam affiliation"}>{p.hist.map((v, i) => <i key={i} title={`${i * 5}–${i * 5 + 5}%: ${num(v)}`} style={{ height: `${Math.max(2, Math.round((v / hmax) * 100))}%` }} className={i * 5 < pol ? "lo" : undefined} />)}</div>
      <p className="meta">{vi ? `Trục ngang: 0% đến 100%, mỗi cột 5%; cột đậm là vùng dưới ngưỡng ${pol}%.` : `Horizontal axis: 0% to 100%, 5% per bar; darker bars lie below the ${pol}% threshold.`}</p>
      <p>{vi ? `Bước 2, hội đồng mô phỏng. ${num(p.n)} chuyên gia mô phỏng chia theo ba lập trường (bao trùm 30%, cân bằng 40%, chặt chẽ 30%). Mỗi người có mức coi trọng riêng giữa hai loại sai sót: loại nhầm người làm việc tại Việt Nam, hoặc đưa nhầm người có liên kết chính ở nước ngoài vào bảng; và chọn ngưỡng làm tổn thất kỳ vọng nhỏ nhất theo mô hình ở bước 1. Sau đó hội đồng bàn bạc ${p.rounds} vòng kiểu Delphi (Dalkey & Helmer, 1963): mỗi người biết trung vị của hội đồng và điều chỉnh một phần ý kiến về phía đó (mô hình đồng thuận của French, 1956 và DeGroot, 1974).` : `Step 2, the simulated panel. ${num(p.n)} simulated experts are split into three stances (inclusive 30%, balanced 40%, strict 30%). Each weighs the two kinds of error differently: wrongly excluding someone who works in Vietnam, or wrongly admitting someone whose primary affiliation is abroad; and picks the threshold with the smallest expected loss under the step-1 model. The panel then deliberates for ${p.rounds} Delphi-style rounds (Dalkey & Helmer, 1963): each member sees the panel median and moves part of the way toward it (consensus models of French, 1956 and DeGroot, 1974).`}</p>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Nhóm / vòng" : "Group / round"}</th><th>{vi ? "Trung vị (%)" : "Median (%)"}</th><th>{vi ? "Khoảng tứ phân vị (%)" : "Interquartile range (%)"}</th></tr></thead>
        <tbody>{p.stances.map((s) => <tr key={s.id}><td>{stanceName(s)} · n = {num(s.n)}</td><td>{num(s.median, 1)}</td><td>{num(s.p25, 1)} – {num(s.p75, 1)}</td></tr>)}
          {p.rounds_.map((r) => <tr key={r.round} className={r.round === p.rounds_.length - 1 ? "all" : undefined}><td>{r.round === 0 ? (vi ? "Cả hội đồng, ý kiến ban đầu" : "Whole panel, initial opinions") : (vi ? `Cả hội đồng, sau vòng ${r.round}` : `Whole panel, after round ${r.round}`)}</td><td>{num(r.median, 1)}</td><td>{num(r.p25, 1)} – {num(r.p75, 1)}</td></tr>)}</tbody></table></div>
      <div className="psp-tw"><table className="psp-t"><thead><tr><th>{vi ? "Ngưỡng" : "Threshold"}</th><th>{vi ? "Hồ sơ bị gắn nhãn" : "Profiles tagged"}</th><th>{vi ? "Loại nhầm (kỳ vọng)" : "Wrongly excluded (expected)"}</th><th>{vi ? "Đưa nhầm (kỳ vọng)" : "Wrongly admitted (expected)"}</th></tr></thead>
        <tbody><tr className="all"><td>{vi ? `Đang áp dụng: ${pol}%` : `In force: ${pol}%`}</td><td>{num(p.sens.find((x) => x.t === pol)?.n ?? 0)}</td><td>{num(p.errorsAtPolicy.expectedWronglyExcluded)}</td><td>{num(p.errorsAtPolicy.expectedWronglyIncluded)}</td></tr>
          <tr><td>{vi ? `Đồng thuận mô phỏng: ${p.errorsAtConsensus.t}%` : `Simulated consensus: ${p.errorsAtConsensus.t}%`}</td><td>—</td><td>{num(p.errorsAtConsensus.expectedWronglyExcluded)}</td><td>{num(p.errorsAtConsensus.expectedWronglyIncluded)}</td></tr></tbody></table></div>
      <p className="meta">{vi ? `Số hồ sơ bị gắn nhãn theo ngưỡng: ${p.sens.map((x) => `${x.t}% → ${num(x.n)}`).join("; ")}.` : `Profiles tagged by threshold: ${p.sens.map((x) => `${x.t}% → ${num(x.n)}`).join("; ")}.`}</p>
      <p>{vi ? `Kết luận. Ngưỡng ProFind đang áp dụng là ${pol}%, ${rel} khoảng đồng thuận của hội đồng mô phỏng (trung vị ${num(c.median, 1)}%, tứ phân vị ${num(c.p25, 1)}–${num(c.p75, 1)}%). Chọn ngưỡng ${pol < c.median ? "thấp" : "cao"} hơn trung vị nghĩa là ${pol < c.median ? "ưu tiên không loại nhầm người làm việc tại Việt Nam; cái giá là một số hồ sơ có liên kết chính ở nước ngoài vẫn có thể được xếp hạng" : "ưu tiên bảng chỉ gồm người có liên kết chính tại Việt Nam; cái giá là một số người làm việc tại Việt Nam có thể bị loại nhầm"} (xem bảng sai sót kỳ vọng). Ngưỡng sẽ được xem xét lại khi có ý kiến chuyên gia thật.` : `Conclusion. ProFind’s threshold is ${pol}%, ${rel} the simulated panel’s consensus (median ${num(c.median, 1)}%, interquartile ${num(c.p25, 1)}–${num(c.p75, 1)}%). A threshold ${pol < c.median ? "below" : "above"} the median ${pol < c.median ? "favours not wrongly excluding people who work in Vietnam, at the cost that some profiles with a primary affiliation abroad may still be ranked" : "favours a table of people whose primary affiliation is in Vietnam, at the cost that some who work in Vietnam may be wrongly excluded"} (see the expected-error table). The threshold will be revisited once real expert opinion is available.`}</p>
      <h3>{vi ? "Lưu ý và giới hạn" : "Notes and limits"}</h3>
      <ul className="psp-ul">
        <li>{vi ? `Hội đồng ${num(p.n)} chuyên gia ở đây là MÔ PHỎNG, không phải ý kiến của người thật. Bằng chứng lấy từ dữ liệu thật ở bước 1; phần giả định là cơ cấu lập trường và mức đánh đổi giữa hai loại sai sót (hạt giống ${p.seed}, mã tại scripts/abroad-panel.mjs, tái lập được).` : `The ${num(p.n)}-expert panel here is a SIMULATION, not real people’s opinions. Evidence comes from real data in step 1; the assumptions are the stance mix and the trade-off between the two kinds of error (seed ${p.seed}, code in scripts/abroad-panel.mjs, reproducible).`}</li>
        <li>{vi ? "Mô hình hai cụm là giả định; người mới chuyển về làm việc tại Việt Nam sau nhiều năm công bố ở nước ngoài, và người Việt công tác ở nước ngoài, có thể nằm ở vùng giữa hoặc vùng thấp. Do đó quy tắc có ngoại lệ do quản trị viên xác nhận và cho phép chủ hồ sơ gửi đính chính." : "The two-cluster model is an assumption; people who recently moved to work in Vietnam after many years of publishing abroad, and Vietnamese scientists working abroad, may fall in the middle or low range. Hence the rule has administrator-confirmed exceptions and lets profile owners submit corrections."}</li>
        <li>{vi ? "Cơ quan ghi trên công trình phụ thuộc vào OpenAlex và có thể thiếu hoặc sai; công trình không có thông tin cơ quan không được tính." : "Affiliations printed on works depend on OpenAlex and may be missing or wrong; works without affiliation information are not counted."}</li>
      </ul>
      <h3>{vi ? "Tài liệu tham khảo" : "References"}</h3>
      <ul className="psp-ul psp-refs">{REFS.map((r) => <li key={r}>{r}</li>)}</ul>
    </section>
  );
}
